### PR TITLE
Fix numpad input on IE.

### LINKED ISSUE #86: IE11 allows users to enter numpad `+-*/` into input
Reported by user. I haven't tried replicating this. Probably worth checking if issue exists in other browsers too.

### PR DESCRIPTION
**Pull request by gordongovan**
I've not got a 'separator' key to test, any volunteers?

This is to fix #86.

### CODE REVIEW

File: src/keyHandlers.js [hunk 1]
```diff
@@ -244,9 +252,13 @@ module.exports = {
    * @param {keyInfo} Information about the pressed key
    */
   onUnknown: function (currentState, keyInfo) {
-    // all printable characters have a key with length of 1 
+    // most printable characters have a key with length of 1,
+    // the numpad characters may have textual keys on older browsers
+    const isPrintableCharacter = keyInfo.keyName.length === 1
+      || numpadKeys.indexOf(keyInfo.keyName) > -1;
+
     // if a character has got this far it is an invalid character
```
Comment (oriondean) [inline src/keyHandlers.js]: Does this comment make sense? Seems like the next line contradicts it!

Comment (gordongovan) [inline src/keyHandlers.js]: Made it clearer that it is about printable characters without modifiers.
